name: build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install System Dependencies
        run: sudo apt-get install -y uild-essential \
          cmake \
          git \
          libasio-dev iproute2 \
          python3 python3-venv python3-pip
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
        with:

          submodule_update: ON
          run_tests: OFF
